---
title: "Variance Ratio on ETF Ownership"
author: "Jonathan Alexander Zeh"
date: "`r Sys.Date()`"
output:
  pdf_document: default
  html_document:
    theme: cerulean
    mainfont: Monaco
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(warning = FALSE, message = FALSE) 
library(tidyverse)
library(ggplot2)
library(caTools)
library(dplyr)
library(purrr)
library(knitr)
library(readxl)
```


# data import
```{r}
df_q <- read.csv("/Users/jonathanzeh/Library/CloudStorage/OneDrive-Personal/BA_Thesis/BA_coding/datasets/eikon_data/variable_data/quarterly_panel_v1.csv")

df_q$date <- as.Date(df_q$date)
```

# clean data
## remove ETF_ownership outliers
```{r}
df_q <- df_q %>%
  filter(ETF_ownership <= 1 | is.na(ETF_ownership) == TRUE, na.rm = TRUE)
```

## min number of observations
```{r}
#lets only allow stocks with more than 20 observations
df_q$stock_RIC <- as.factor(df_q$stock_RIC)

observation_count <- df_q %>%
  mutate(observation = ifelse(is.na(Variance_Ratio) == TRUE, 0, 1)) %>%
  group_by(stock_RIC) %>%
  summarise(n_observations = sum(observation)) %>%
  filter(n_observations > 8)
              

### only keep observations that are in this data frame
stocks_to_keep <- observation_count$stock_RIC
df_q <- df_q %>%
  filter(stock_RIC %in% stocks_to_keep)
```

## winsorize ETF_ownership
```{r}
winsorize_var <- function(x, probs = c(0.01, 0.99)) {
  Winsorize(x, probs = probs, na.rm = TRUE)
}

df_q <- df_q %>%
  group_by(stock_RIC) %>%
  mutate(ETF_ownership_winsorized = winsorize_var(ETF_ownership),
         Variance_Ratio_winsorized = winsorize_var(Variance_Ratio),
         abs_Variance_Ratio_winsorized = winsorize_var(abs_Variance_Ratio))
```

## standardizing 
```{r}
df_q <- df_q %>%
  mutate(final_ETF_ownership = scale(ETF_ownership_winsorized),
         final_Variance_Ratio = scale(Variance_Ratio),
         final_abs_Variance_Ratio = scale(abs_Variance_Ratio_winsorized),
         final_FUND_ownership = scale(FUND_ownership))
```

## construct new variables
```{r}
df_q <- df_q %>%
  mutate(log_market_cap = log(market_cap),
         inv_price = 1/price)
```

## clean amihud_ratio
```{r}
df_q$amihud_ratio[is.infinite(df_q$amihud_ratio)] <- NA
```

# regression setups
## linear models
```{r}
mod_1_q <- lm(final_Variance_Ratio ~ final_ETF_ownership, data = df_q)
summary(mod_1_q)

######## split
df_q <- df_q %>%
  mutate(year = as.numeric(format(date, "%Y")))

df_q_1 <- df_q %>%
  filter(year < 2020)

df_q_2 <- df_q %>%
  filter(year > 2020)

tmp2 <- lm(final_Variance_Ratio ~ final_ETF_ownership, data = df_q_2)
tmp1 <- lm(final_Variance_Ratio ~ final_ETF_ownership, data = df_q_1)

summary(tmp2)
summary(tmp1)
```

## panel regression: time and entity fixed
```{r}
library(plm)
library(zoo)

fixed_effects_coefficients_q <- function(df){
  df$quarter <- as.yearqtr(df$date, format = "%Y-%q") 
  df$quarter <- as.factor(df$quarter)
  #######################################################
  pdata <- pdata.frame(df, index = c("stock_RIC", "quarter"))
   # Convert date to quarterly format
  #######################################################
  
  fe_model_1_q <- plm(final_Variance_Ratio ~ final_ETF_ownership + log_market_cap + 
                    inv_price + cumulative_return_12m + amihud_ratio + FUND_ownership, 
                    data = pdata, model = "within")
  return(summary(fe_model_1_q))
}

fixed_effects_coefficients_q(df_q)


df_coefficients_q <- tibble(
  variables = c("ETF_ownership", "log_market_cap", "inv_price",
                                "cumulative_return_12m", "amihud_ratio",
                                "FUND_ownership"),
  coefficents_2010_2019 = fixed_effects_coefficients_q(df_q_1)$coefficients[, c(1)],
  coefficients_2020_2023 = fixed_effects_coefficients_q(df_q_2)$coefficients[, c(1)],
)
print(df_coefficients_q)
```






#plot
```{r, eval = F, include = F}
ggplot(df %>% filter(stock_RIC == "ZURN.S"))+
geom_line(aes(x=date, y= ETF_ownership))


basic_plot <- function(stock) {
  df_tmp <- df[, c("date", "stock_RIC", "ETF_ownership", "Variance_Ratio")] %>% 
    filter(stock_RIC == stock)
  df_tmp <- na.omit(df_tmp)
  
  par(mfrow = c(2, 1), mar = c(2, 0, 2, 0))
  plot(x = as.Date(df_tmp$date), y = df_tmp$ETF_ownership)
  plot(x = as.Date(df_tmp$date), y = df_tmp$Variance_Ratio)
  
  
}

basic_plot("ZURN.S")
basic_plot("ASML.S")
```

## plot all data points
```{r}
plot(x = df$ETF_ownership, y = df$abs_Variance_Ratio, col = rgb(0, 0, 0, 0.012),
     xlim = c(0, 0.3), ylim = c(0, 3),
     main = "ETF Ownership against Variance Ratio",
     ylab = "abs(Variance Ratio)",
     xlab = "ETF Ownership")

```


## stock level data
```{r}
stock_level_data <-read_csv(
  "/Users/jonathanzeh/Library/CloudStorage/OneDrive-Personal/BA_Thesis/BA_coding/datasets/eikon_data/stock_level_data/stock_level_data.csv")

selected_dates <- seq.Date(from = as.Date("2019-01-01"), to = as.Date("2019-07-30"), by = "day")

ZURN_data <- stock_level_data %>%
  filter(stock_RIC == "ZURN.S" & date %in% selected_dates)

plot(ZURN_data$date, ZURN_data$market_cap)



stock_level_data <- stock_level_data %>%
  filter(stock_RIC == "ZURN.S")



```


## m_stock_level data
```{r}
m_stock_level_data <- read_csv("/Users/jonathanzeh/Library/CloudStorage/OneDrive-Personal/BA_Thesis/BA_coding/datasets/eikon_data/stock_level_data/m_stock_level_data.csv")

m_stock_level_data %>%
  filter(stock_RIC == "ZURN.S" & date %in% selected_dates)
```

