# data preperation for quality check
```{r, include = F}
library(ggplot2)
library(dplyr)
library(tidyverse)


####################################################### cleaned data set
raw_data <- read.csv("/Users/jonathanzeh/Library/CloudStorage/OneDrive-Personal/RStudio/BA_Thesis/merged_data_sets/stoxx_europe_600_merge_raw.csv")

####### rename columns
colnames(raw_data) = c("ticker", "name", "sector", "asset_class","market_cap", "weight", "nominal_value", "nominal", "price", "country", "stock_exchange","currency","date", "consistent_name")

raw_data$weight[raw_data$weight == ""] <- NA
raw_data <- na.omit(raw_data, subset = "weight")

cleaned_data <- raw_data[, c("ticker", "name", "consistent_name", "weight", "price", "date")]

####### data
cleaned_data$date <- as.Date(as.character(cleaned_data$date))
cleaned_data$weight <- as.numeric(gsub(",", ".", cleaned_data$weight))
cleaned_data$price <- as.numeric(gsub(",", ".", cleaned_data$price))
#cleaned_data$market_cap <- as.numeric(gsub(",", ".", cleaned_data$market_cap))

#### zero weights
cleaned_data <- filter(cleaned_data, weight != 0)


# Assuming cleaned_data is already defined
# Creating average_weight_data with summarise(), which drops the grouping
average_weight_data <- cleaned_data %>%
  group_by(consistent_name) %>%
  summarise(average_weight = mean(weight, na.rm = TRUE), .groups = 'drop')

# Convert to tibble
df_subsets <- as_tibble(average_weight_data)

# Ensure the name column is not a list
# Converting the 'name' column to a character vector if it's a list
if (is.list(df_subsets$consistent_name)) {
  df_subsets$consistent_name <- sapply(df_subsets$conistent_name, `[`, 1)
}

# Sort tibble after average weight
df_subsets <- arrange(df_subsets, desc(average_weight))

# Creating an index vector
n <- length(df_subsets$consistent_name)
values <- c(1:n)
df_subsets$index_vector <- cut(values, breaks = seq(1, n, by = 4), 
                               include.lowest = TRUE, labels = FALSE)

# Checking the result
print(df_subsets)
```

# plots v2
```{r}
color_palette <- c("blue", "red", "green", "black", "#f700ae")

for (i in 1:max(df_subsets$index_vector, na.rm = TRUE)) {
  subset_names <- df_subsets$consistent_name[df_subsets$index_vector == i]
  subset_data <- filter(cleaned_data, consistent_name %in% subset_names)
  subset_data[] <- lapply(subset_data, function(x) {
    if (is.list(x)) unlist(x) else x
  })
  # Generate and save the plot
    p <- ggplot(subset_data, aes(x = date, y = weight, 
                                 color = factor(consistent_name))) +
      geom_rect(aes(xmin = as.Date("2016-12-30"), 
                    xmax = as.Date("2017-07-06"), ymin = -Inf,
                    ymax = Inf), fill = "gray", alpha = 0.1, colour = NA) +
      geom_line(size = 0.35) +
      theme_minimal() +
      theme(legend.position = "bottom",  
            legend.text = element_text(size = 6),  # Adjust text size
            legend.key.size = unit(0.2, "cm")) +  # Adjust key size
    labs(title = 
           paste("Stock Weights Over Time - iShares STOXX Europe 600 ETF",
                 "Subset", i), x = "Date", y = "Weight") +
    scale_color_manual(values = color_palette) +
    guides(color = guide_legend(title = NULL))
    print(p)
}
```